<a href="https://colab.research.google.com/github/Venni2911/LogicMojo-AI-ML-Sept25-VenniRaj/blob/main/Venni_CW_19_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5 ])
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(arr_2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr_3D = np.array([[1,2,3],[4,5,6],[7,8,9]],
                  [[1,2,3],[4,5,6],[7,8,9]],
                  [[1,2,3],[4,5,6],[7,8,9]])

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [ ]:
arr_tup = np.array((1,2,3,4,5))
arr_tup

array([1, 2, 3, 4, 5])

In [ ]:
zeros = np.zeros((3,3,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
ones = np.ones((6,6))
ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
r = np.full((3,3),5)
r

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
r = np.arange(5,15)
r

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
r = np.linspace(5,15,5)
r
r1 = np.linspace(0,1,5)
r1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# Reshape
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr
new_rr = np.reshape(arr,(3,4))
new_rr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
new_rr.reshape((12))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
new_rr.reshape(3,4,-1)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]]])

In [ ]:
new_rr.reshape((4,-1))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
new_rr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
ss = np.array([1,6,7,8,9,10,2,3,4,5,11,12])
np.sort(ss)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.sort(np.array(['dcf','xdf','abc']))


array(['abc', 'dcf', 'xdf'], dtype='<U3')

In [ ]:
ss
-np.sort(-ss)

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
ss[2:4]

array([7, 8])

In [ ]:
new_rr.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
new_rr.reshape(2,-1)[0:1,1:4]

array([[2, 3, 4]])

In [ ]:
new_rr.reshape(2,-1)[0:2,1:4]

array([[ 2,  3,  4],
       [ 8,  9, 10]])

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
a+b

array([ 7,  9, 11, 13, 15])

In [ ]:
np.add(a,b)

array([ 7,  9, 11, 13, 15])

In [ ]:
b-a

array([5, 5, 5, 5, 5])

In [ ]:
a-b
np.subtract(a,b)

array([-5, -5, -5, -5, -5])

In [ ]:
np.multiply(a,b)

array([ 6, 14, 24, 36, 50])

In [ ]:
np.divide(a,b)
a/b
print(a/b)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
np.mean(a)

np.float64(3.0)

In [ ]:
np.maximum(a,b)

array([ 6,  7,  8,  9, 10])

In [ ]:
np.std(a)

np.float64(1.4142135623730951)

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
# a+b
np.multiply(a,b)

array([ 6, 14, 24, 36, 50])

In [ ]:
## Vector

## 1D numpy aray are called vectors and used in ML

a * b

array([ 6, 14, 24, 36, 50])

In [ ]:
arr = np.array([[1,2],[4,5]])
arr2 = np.array([[1,2],[4,5]])

np.dot(a,b)
np.dot(arr,arr2)

array([[ 9, 12],
       [24, 33]])

In [ ]:
arr2.T

array([[1, 4],
       [2, 5]])

In [ ]:
arr2

array([[1, 2],
       [4, 5]])